pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }

    def props = new Properties()
    file('gradle.properties').withInputStream { props.load(it) }

    plugins {
        id 'net.neoforged.moddev'                      version "${props.moddev_version}"
        id 'org.jetbrains.kotlin.jvm'                  version "${props.kotlin_version}"
        id 'org.jetbrains.kotlin.plugin.serialization' version "${props.kotlin_version}"
        id 'org.jetbrains.kotlin.plugin.lombok'        version "${props.kotlin_version}"
        id 'io.freefair.lombok'                        version "${props.lombok_plugin_version}"
        id 'com.gradleup.shadow'                       version "${props.shadow_version}"
    }
}

rootProject.name = 'LogisticsPipes'
