package logisticspipes.recipes;

import net.minecraft.core.registries.BuiltInRegistries;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.resources.ResourceLocation;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import lombok.AllArgsConstructor;
import lombok.Getter;

import logisticspipes.LPConstants;

public class RecipeManager {

	public static final List<IRecipeProvider> recipeProvider = new ArrayList<>();
	public static final LocalCraftingManager craftingManager = new LocalCraftingManager();

	public static void loadRecipes() {
		recipeProvider.forEach(IRecipeProvider::loadRecipes);
	}

	@AllArgsConstructor
	@Getter
	public static class RecipeIndex {

		private char index;
		private Object value;
	}

	@AllArgsConstructor
	@Getter
	public static class RecipeLayout {

		private String line1;
		private String line2;
		private String line3;
	}

	@AllArgsConstructor
	@Getter
	public static class RecipeLayoutSmall {

		private String line1;
		private String line2;
	}

	@AllArgsConstructor
	@Getter
	public static class RecipeLayoutSmaller {

		private String line1;
	}

	public static class LocalCraftingManager {

		private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

		/** Recipes generated by providers at startup, served via LPRecipePack virtual data pack. */
		public final Map<ResourceLocation, String> virtualRecipes = new LinkedHashMap<>();

		public LocalCraftingManager() {
		}

		public void addRecipe(@Nonnull ItemStack stack, Object... objects) {
			List<Object> result = new ArrayList<>();
			final boolean[] addRecipe = { true };
			Object layout = null;
			List<RecipeIndex> indices = new ArrayList<>();

			Arrays.stream(objects).forEach(o -> {
				if (!addRecipe[0]) return;
				if (o instanceof RecipeLayout || o instanceof RecipeLayoutSmall || o instanceof RecipeLayoutSmaller) {
					result.add(o);
				} else if (o instanceof RecipeIndex) {
					RecipeIndex ri = (RecipeIndex) o;
					result.add(ri.getIndex());
					result.add(ri.getValue());
					if (ri.getValue() == null) {
						addRecipe[0] = false;
					} else {
						indices.add(ri);
					}
				} else {
					result.add(o);
				}
			});
			if (!addRecipe[0]) return;

			// Find layout object
			for (Object o : objects) {
				if (o instanceof RecipeLayout || o instanceof RecipeLayoutSmall || o instanceof RecipeLayoutSmaller) {
					layout = o;
					break;
				}
			}
			if (layout == null) return;

			String json = dumpRecipe(stack, layout, indices.toArray(new RecipeIndex[0]));
			if (json != null) {
				ResourceLocation loc = getFreeRecipeResourceLocation(stack.getItem());
				virtualRecipes.put(loc, json);
			}
		}

		/** Generates a shaped crafting recipe JSON string. Returns null if any ingredient is unhandled. */
		private String dumpRecipe(@Nonnull ItemStack result, Object layout, RecipeIndex... indices) {
			JsonObject obj = new JsonObject();
			JsonArray pattern = new JsonArray();
			JsonObject keys = new JsonObject();
			obj.addProperty("type", "minecraft:crafting_shaped");

			if (layout instanceof RecipeLayout) {
				pattern.add(((RecipeLayout) layout).getLine1());
				pattern.add(((RecipeLayout) layout).getLine2());
				pattern.add(((RecipeLayout) layout).getLine3());
			} else if (layout instanceof RecipeLayoutSmall) {
				pattern.add(((RecipeLayoutSmall) layout).getLine1());
				pattern.add(((RecipeLayoutSmall) layout).getLine2());
			} else if (layout instanceof RecipeLayoutSmaller) {
				pattern.add(((RecipeLayoutSmaller) layout).getLine1());
			}

			for (RecipeIndex index : indices) {
				// Only include keys that actually appear in the pattern
				String patternStr = pattern.toString();
				if (!patternStr.contains(String.valueOf(index.getIndex()))) continue;

				JsonObject key = new JsonObject();
				if (index.getValue() instanceof String) {
					// Ore dict tag → forge tag
					key.addProperty("tag", oreDictToTag((String) index.getValue()));
				} else if (index.getValue() instanceof ItemStack) {
					ItemStack stack = (ItemStack) index.getValue();
					key.addProperty("item", BuiltInRegistries.ITEM.getKey(stack.getItem()).toString());
				} else if (index.getValue() instanceof Item) {
					key.addProperty("item", BuiltInRegistries.ITEM.getKey((Item) index.getValue()).toString());
				} else if (index.getValue() instanceof Block) {
					key.addProperty("item", BuiltInRegistries.ITEM.getKey(Item.BY_BLOCK.get((Block) index.getValue())).toString());
				} else if (index.getValue() instanceof NBTIngredient) {
					NBTIngredient nbtIng = (NBTIngredient) index.getValue();
					key = nbtIng.toJson().getAsJsonObject();
				} else {
					// Unhandled type — skip this recipe
					return null;
				}
				keys.add(index.getIndex() + "", key);
			}

			JsonObject r = new JsonObject();
			r.addProperty("item", BuiltInRegistries.ITEM.getKey(result.getItem()).toString());
			if (result.getCount() > 1) r.addProperty("count", result.getCount());
			obj.add("result", r);
			obj.add("key", keys);
			obj.add("pattern", pattern);

			return GSON.toJson(obj);
		}

		/** Maps 1.12.2 ore dict names to NeoForge 1.20.1 tag paths. */
		private static String oreDictToTag(String oreDict) {
			switch (oreDict) {
				case "ingotIron":        return "forge:ingots/iron";
				case "ingotGold":        return "forge:ingots/gold";
				case "nuggetGold":       return "forge:nuggets/gold";
				case "dustRedstone":     return "forge:dusts/redstone";
				case "gemLapis":         return "forge:gems/lapis";
				case "gemDiamond":       return "forge:gems/diamond";
				case "gemQuartz":        return "forge:gems/quartz";
				case "dustGlowstone":    return "forge:dusts/glowstone";
				case "dyeBlack":         return "forge:dyes/black";
				case "dyeRed":           return "forge:dyes/red";
				case "dyeGreen":         return "forge:dyes/green";
				case "dyeBrown":         return "forge:dyes/brown";
				case "dyeBlue":          return "forge:dyes/blue";
				case "dyePurple":        return "forge:dyes/purple";
				case "dyeCyan":          return "forge:dyes/cyan";
				case "dyeLightGray":     return "forge:dyes/light_gray";
				case "dyeGray":          return "forge:dyes/gray";
				case "dyePink":          return "forge:dyes/pink";
				case "dyeLime":          return "forge:dyes/lime";
				case "dyeYellow":        return "forge:dyes/yellow";
				case "dyeLightBlue":     return "forge:dyes/light_blue";
				case "dyeMagenta":       return "forge:dyes/magenta";
				case "dyeOrange":        return "forge:dyes/orange";
				case "dyeWhite":         return "forge:dyes/white";
				case "paper":            return "forge:paper";
				default:
					// Unknown ore dict — return as forge tag guess
					return "forge:" + oreDict;
			}
		}

		public void addShapelessResetRecipe(Item item, int meta) {
			// meta was a 1.12.2 damage value — ignored in 1.20.1 (no damage-based variants)
			ResourceLocation itemKey = net.minecraft.core.registries.BuiltInRegistries.ITEM.getKey(item);
			if (itemKey == null) return;
			ResourceLocation loc = getFreeRecipeResourceLocation(item);
			JsonObject json = new JsonObject();
			json.addProperty("type", ShapelessResetRecipe.ID.toString());
			json.addProperty("item", itemKey.toString());
			virtualRecipes.put(loc, new Gson().toJson(json));
		}
	}

	private static ResourceLocation getFreeRecipeResourceLocation(@Nonnull ItemStack stack) {
		return getFreeRecipeResourceLocation(stack.getItem());
	}

	private static ResourceLocation getFreeRecipeResourceLocation(Item item) {
		ResourceLocation baseLoc = ResourceLocation.fromNamespaceAndPath(LPConstants.LP_MOD_ID, BuiltInRegistries.ITEM.getKey(item).getPath());
		ResourceLocation recipeLoc = baseLoc;
		int index = 0;
		while (craftingManager.virtualRecipes.containsKey(recipeLoc)) {
			index++;
			recipeLoc = ResourceLocation.fromNamespaceAndPath(LPConstants.LP_MOD_ID, BuiltInRegistries.ITEM.getKey(item).getPath() + "_" + index);
		}
		return recipeLoc;
	}
}
