modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "morph"
version = "${version}"
displayName = "Morph"
authors = "NoZeroG"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.morph]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.morph]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.morph]]
modId = "architectury"
type = "required"
versionRange = "[13.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "morph.mixins.json"
